#!/usr/bin/env bash
# Build a personal FigureViewer.app that wraps the conda/figviewer CLI.
# Usage:
#   ./packaging/macos/install_app.sh
#   ./packaging/macos/install_app.sh --icon path/to/logo_1024.png
#   ./packaging/macos/install_app.sh --prefix ~/Applications
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PREFIX="${HOME}/Applications"
ICON_SRC=""
ENV_NAME="figviewer"
PYTHON_BIN=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --icon) ICON_SRC="$2"; shift 2 ;;
    --python) PYTHON_BIN="$2"; shift 2 ;;
    --env) ENV_NAME="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,8p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

resolve_python() {
  if [[ -n "${PYTHON_BIN}" && -x "${PYTHON_BIN}" ]]; then
    echo "${PYTHON_BIN}"
    return
  fi
  if command -v conda >/dev/null 2>&1; then
    local cand
    cand="$(conda run -n "${ENV_NAME}" which python 2>/dev/null || true)"
    if [[ -n "${cand}" && -x "${cand}" ]]; then
      echo "${cand}"
      return
    fi
  fi
  if command -v figureviewer >/dev/null 2>&1; then
    local fv
    fv="$(command -v figureviewer)"
    if head -1 "${fv}" | grep -q '^#!'; then
      local shebang
      shebang="$(head -1 "${fv}" | sed 's/^#!//')"
      if [[ -x "${shebang}" ]]; then
        echo "${shebang}"
        return
      fi
    fi
  fi
  if command -v figuregallery >/dev/null 2>&1; then
    # Prefer the interpreter that owns the entry point.
    local fg
    fg="$(command -v figuregallery)"
    if head -1 "${fg}" | grep -q '^#!'; then
      local shebang
      shebang="$(head -1 "${fg}" | sed 's/^#!//')"
      # shebang may be "/usr/bin/env python" — fall through
      if [[ -x "${shebang}" ]]; then
        echo "${shebang}"
        return
      fi
    fi
  fi
  echo "error: could not find Python for env '${ENV_NAME}'. Pass --python /path/to/python" >&2
  exit 1
}

PYTHON_BIN="$(resolve_python)"
if ! "${PYTHON_BIN}" -c "import figureviewer, figuregallery, PyQt6" 2>/dev/null; then
  echo "error: ${PYTHON_BIN} cannot import figureviewer + figuregallery + PyQt6" >&2
  echo "       activate/install the figviewer env and \`pip install -e .\` first" >&2
  exit 1
fi

APP_NAME="Figure Viewer.app"
APP_DIR="${PREFIX}/${APP_NAME}"
CONTENTS="${APP_DIR}/Contents"
MACOS="${CONTENTS}/MacOS"
RESOURCES="${CONTENTS}/Resources"
ICONSET="${TMPDIR:-/tmp}/FigureViewer.iconset"
MASTER_PNG="${ROOT}/assets/figureviewer/icon_1024.png"
LEGACY_APP="${PREFIX}/Figure Gallery.app"

mkdir -p "${MACOS}" "${RESOURCES}"

if [[ -n "${ICON_SRC}" ]]; then
  if [[ ! -f "${ICON_SRC}" ]]; then
    echo "error: icon not found: ${ICON_SRC}" >&2
    exit 1
  fi
  mkdir -p "$(dirname "${MASTER_PNG}")"
  cp "${ICON_SRC}" "${MASTER_PNG}"
fi

if [[ ! -f "${MASTER_PNG}" ]]; then
  echo "error: missing app icon: ${MASTER_PNG}" >&2
  echo "       add assets/figureviewer/icon_1024.png or pass --icon path/to/1024.png" >&2
  exit 1
fi

# Build .icns from 1024 master (macOS iconutil).
rm -rf "${ICONSET}"
mkdir -p "${ICONSET}"
for px in 16 32 128 256 512; do
  sips -z "${px}" "${px}" "${MASTER_PNG}" --out "${ICONSET}/icon_${px}x${px}.png" >/dev/null
  dbl=$((px * 2))
  sips -z "${dbl}" "${dbl}" "${MASTER_PNG}" --out "${ICONSET}/icon_${px}x${px}@2x.png" >/dev/null
done
# 1024 is only used as 512@2x (already written). iconutil also wants icon_512x512@2x.
cp "${MASTER_PNG}" "${ICONSET}/icon_512x512@2x.png"
iconutil -c icns "${ICONSET}" -o "${RESOURCES}/AppIcon.icns"
rm -rf "${ICONSET}"

cp "${ROOT}/packaging/macos/Info.plist" "${CONTENTS}/Info.plist"

LAUNCHER="${MACOS}/FigureViewer"
cat > "${LAUNCHER}" <<EOF
#!/bin/bash
# Auto-generated by packaging/macos/install_app.sh — do not edit by hand.
set -euo pipefail
export FIGUREVIEWER_QUIET=1
export FIGUREGALLERY_QUIET=1
export FIGUREVIEWER_APP_ICON="\$(cd "\$(dirname "\$0")/../Resources" && pwd)/AppIcon.icns"
export FIGUREGALLERY_APP_ICON="\${FIGUREVIEWER_APP_ICON}"
# Keep PATH usable for anything the env expects.
export PATH="$(dirname "${PYTHON_BIN}"):\${PATH}"
exec "${PYTHON_BIN}" -m figureviewer.cli --desktop "\$@"
EOF
chmod +x "${LAUNCHER}"

# Refresh Launch Services / icon cache hints.
if command -v touch >/dev/null; then
  touch "${APP_DIR}"
fi

# Remove the old single-purpose Gallery app if present (same prefix).
if [[ -d "${LEGACY_APP}" ]]; then
  rm -rf "${LEGACY_APP}"
  echo "Removed legacy: ${LEGACY_APP}"
fi

echo "Installed: ${APP_DIR}"
echo "Python:    ${PYTHON_BIN}"
echo "Icon:      ${MASTER_PNG}"
echo
echo "Open with Spotlight (Figure Viewer) or:"
echo "  open \"${APP_DIR}\""
echo "Modes: toolbar toggles Compare ↔ Browse (Ctrl+1 / Ctrl+2)"
echo "Drag to the Dock if you want it pinned."
